name: test-cases

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install coverage
    - name: Run Testcases
      run: pytest .
